name: SQLFluff Lint

on: [push, pull_request]

permissions:
  contents: write
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Identify new or modified files
      id: file_changes
      run: |
        echo "Identifying new or modified files..."
        files=$(git diff --name-only HEAD^ HEAD| grep '\.sql$' | tr '\n' ' ' )
        if [ -z "$files" ]; then
          echo "No new or modified files."
        else
          echo "New or modified files:"
          echo "$files"
          echo "FILES=$files" >> $GITHUB_ENV
        fi

    - name: Install SQLFluff
      run: pip install sqlfluff

    - name: Lint SQL
      id: lint_sql
      run: |
        if [ -n "${{ env.FILES }}" ]; then
        echo "${{env.FILES}}" | xargs sqlfluff lint
        else
          echo "No files to process."
        fi
        
    - name: Fix SQL if Lint Fails
      id: fix_sql
      if: ${{ steps.lint_sql.outcome == 'failure' && github.event_name == 'push' }}
      run: |
        echo "${{env.FILES}}" | xargs sqlfluff fix
      continue-on-error: true

    - name: Push fixed files
      if: ${{ steps.fix_sql.conclusion == 'success' && github.event_name == 'push' }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m 'Auto-fix SQL file(s) with SQLFluff'
        git push origin HEAD:${{ github.ref }}
