name: SQLFluff Lint

on: [push, pull_request]

permissions:
  contents: write
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Identify new or modified files
      id: file_changes
      run: |
        echo "Identifying new or modified files..."
        FILES=$(git diff --name-only)
        if [ -z "$FILES" ]; then
          echo "No new or modified files."
        else
          echo "New or modified files:"
          echo "$FILES"
          echo "FILES=$FILES" >> $GITHUB_ENV
        fi

    - name: test environment
    - run: echo ${{ env.FILES }}"

    - name: Install SQLFluff
      run: pip install sqlfluff

    - name: Lint SQL
      id: lint_sql
      run: |
        if [ -n ${{ env.FILES }}" ]; then
        echo ${{ env.FILES }}" | tr ' ' '\n' | grep '\.sql$' | xargs sqlfluff lint
        else
          echo "No files to process."
        fi
        
    - name: Fix SQL if Lint Fails
      if: steps.lint_sql.conclusion == 'failure'
      run: |
        echo "${{ steps.file_changes.outputs.changed_files }}" | tr ' ' '\n' | grep '\.sql$' | xargs sqlfluff fix
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m 'Auto-fix SQL file(s) with SQLFluff'
        git push origin HEAD:${{ github.ref }}
